--TABLA QUE REPRESENTA A UN ESTUDIANTE DE SERVICIO COMUNITARIO
CREATE TABLE ESTUDIANTE
  ( NOMBRE     VARCHAR(30) NOT NULL, --NOMBRES DEL ESTUDIANTE
    APELLIDO   VARCHAR(40) NOT NULL, --APELLIDOS DEL ESTUDIANTE
    CARNET     VARCHAR(9)  NOT NULL, --CARNET DEL ESTUDIANTE EJ. 12-34567
    DIRECCION  VARCHAR(40) NOT NULL, --DIRECCION DE HOGAR DEL ESTUDIANTE
    EMAIL      VARCHAR(30) NOT NULL, --DIRECCION DE CORREO ELECTRONICO DEL ESTUDIANTE
    ESTADO     VARCHAR(30) NOT NULL, --ESTADO ACTIVO PARA REFLEJAR QUE SE ENCUENTRA EN EL SISTEMA BETA
    CELULAR    VARCHAR(20) NOT NULL, --NUMERO TELEFONICO DE CONTACTO PERSONAL
    ACUMULADO  FLOAT       NOT NULL, --TOTAL DE HORAS ACUMULADAS DEL SERVICIO COMUNITARIO

    CONSTRAINT DOM_ACUMULADO CHECK (ACUMULADO >= 0),
    CONSTRAINT DOM_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT PK_ESTUDIANTE PRIMARY KEY(CARNET)
  );


--TABLA QUE REFLEJA HORAS DE LABOR SOCIAL CUMPLIDAS POR DIA
CREATE TABLE LABOR
  ( SERIE         SERIAL(0)   NOT NULL, --IDENTIFICADOR
    HORA_INICIO   VARCHAR(60) NOT NULL, --HORA DE INICIO DE LA LABOR SOCIAL EN EL DIA
    HORA_FIN      VARCHAR(60) NOT NULL, --HORA DE CULMINACION DEL SERVICIO SOCIAL EN EL DIA
    OBSERVACION   VARCHAR(60) NOT NULL, --OBSERVACIONES POR PARTE DEL ENCARGADO
    FECHA         DATE        NOT NULL, --FECHA ASOCIADA A LA LABOR SOCIAL
    TIEMPO_TOTAL  FLOAT       NOT NULL, --TIEMPO ACREDITADO POR LA LABOR SOCIAL

    CONSTRAINT DOM_TIEMPO_TOTAL CHECK (TIEMPO_TOTAL >= 0)
    CONSTRAINT PK_LABOR PRIMARY KEY(SERIE)
  );


--TABLA QUE ASOCIA UN TIEMPO DE LABOR SOCIAL CON UN ESTUDIANTE
CREATE TABLE CUMPLE
  ( CARNET         VARCHAR(10) NOT NULL, --CARNET IDENTIFICADOR DEL ESTUDIANTE
    SERIE          NUMBER(10)  NOT NULL, --NUMERO DE SERIE QUE IDENTIFICA A LA LABOR SOCIAL
    POSTIZA_CUMPLE SERIAL(0)   NOT NULL, --POSTIZA PARA IDENTIFICAR LA RELACION

    CONSTRAINT PK_CUMPLE PRIMARY KEY (CARNET, SERIE),
    CONSTRAINT FK_ESTUDIANTE FOREING KEY(CARNET)
      REFERENCES ESTUDIANTE(CARNET),
    CONSTRAINT FK_LABOR FOREING KEY(SERIE)
      REFERENCES LABOR(SERIE)
  );

