--TABLA QUE REPRESENTA A UN ESTUDIANTE DE SERVICIO COMUNITARIO
CREATE TABLE ESTUDIANTE
  ( NOMBRE     VARCHAR(30) NOT NULL, --NOMBRES DEL ESTUDIANTE
    APELLIDO   VARCHAR(40) NOT NULL, --APELLIDOS DEL ESTUDIANTE
    CARNET     VARCHAR(8)  NOT NULL, --CARNET DEL ESTUDIANTE EJ. 12-34567
    DIRECCION  VARCHAR(40) NOT NULL, --DIRECCION DE HOGAR DEL ESTUDIANTE
    EMAIL      VARCHAR(30) NOT NULL, --DIRECCION DE CORREO ELECTRONICO DEL ESTUDIANTE
    ESTADO     VARCHAR(30) NOT NULL, --ESTADO ACTIVO PARA REFLEJAR QUE SE ENCUENTRA EN EL SISTEMA BETA
    CELULAR    VARCHAR(20) NOT NULL, --NUMERO TELEFONICO DE CONTACTO PERSONAL

    CONSTRAINT DOM_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT PK_ESTUDIANTE PRIMARY KEY(CARNET)
  );


--TABLA QUE REFLEJA HORAS DE LABOR SOCIAL CUMPLIDAS POR DIA
CREATE TABLE LABOR
  ( HORA_INICIO   VARCHAR(60) NOT NULL, --HORA DE INICIO DE LA LABOR SOCIAL EN EL DIA
    HORA_FIN      VARCHAR(60) NOT NULL, --HORA DE CULMINACION DEL SERVICIO SOCIAL EN EL DIA
    OBSERVACION   VARCHAR(60) NOT NULL, --OBSERVACIONES POR PARTE DEL ENCARGADO
    FECHA         DATE        NOT NULL, --FECHA ASOCIADA A LA LABOR SOCIAL
    CARNET_LABOR  VARCHAR(8)  NOT NULL, --CARNET IDENTIFICADOR DEL ESTUDIANTE
    TIEMPO_TOTAL  REAL        NOT NULL, --TIEMPO ACREDITADO POR LA LABOR SOCIAL

    CONSTRAINT PK_LABOR PRIMARY KEY(CARNET_LABOR,FECHA,HORA_INICIO),
    CONSTRAINT FK_ESTUDIANTE FOREIGN KEY(CARNET_LABOR)
      REFERENCES ESTUDIANTE(CARNET),
    CONSTRAINT DOM_TIEMPO_TOTAL CHECK (TIEMPO_TOTAL >= 0)
  );
