/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Graphic;
import java.util.regex.Pattern;

/**
 * Jform que permite agregar horas
 * @author johndelgado
 */
public class Agregar_horas extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_horas
     */
    private Window padre = (Window) this.getParent();
    public Agregar_horas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Obs = new javax.swing.JPanel();
        Carnet = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        fin = new javax.swing.JLabel();
        f_carnet = new javax.swing.JTextField();
        f_fecha = new javax.swing.JTextField();
        f_inicio = new javax.swing.JTextField();
        f_fin = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        fin1 = new javax.swing.JLabel();
        f_obs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Carnet.setText("Carnet");

        Fecha.setText("Fecha");

        inicio.setText("Hora de inicio");

        fin.setText("Hora de fin");

        f_inicio.setText("");

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        fin1.setText("Observaciones");

        f_obs.setText("Ninguna Observacion");

        jLabel1.setText("Atención, las horas deben estar en formato militar!");

        jLabel2.setText("DD-MM-AAAA");

        jLabel3.setText("12-34567");

        jLabel4.setText("13:00");

        jLabel5.setText("16:00");

        jLabel6.setText("Agregar horas de servicio comunitario");

        javax.swing.GroupLayout ObsLayout = new javax.swing.GroupLayout(Obs);
        Obs.setLayout(ObsLayout);
        ObsLayout.setHorizontalGroup(
            ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObsLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ObsLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObsLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ObsLayout.createSequentialGroup()
                                .addComponent(f_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(ObsLayout.createSequentialGroup()
                                .addComponent(f_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(316, 316, 316))
                    .addGroup(ObsLayout.createSequentialGroup()
                        .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ObsLayout.createSequentialGroup()
                                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fin1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ObsLayout.createSequentialGroup()
                                        .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Carnet)
                                            .addComponent(inicio)
                                            .addComponent(Fecha)
                                            .addComponent(fin))
                                        .addGap(4, 4, 4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ObsLayout.createSequentialGroup()
                                        .addComponent(f_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(ObsLayout.createSequentialGroup()
                                        .addComponent(f_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar)
                .addGap(246, 246, 246))
        );
        ObsLayout.setVerticalGroup(
            ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObsLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ObsLayout.createSequentialGroup()
                        .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Carnet)
                            .addComponent(f_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fecha))
                    .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(f_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inicio)
                    .addComponent(f_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(regresar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Obs, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Obs, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se agrega un estudiante al presionar el boton agregar
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        Boolean cumple = false;
        Boolean existe = false;
        Hora resultado = null;
        Hora inicioH = null;
        Hora finH = null;
        // a partir de aqui son verificaciones de los campos de los formularios
        if (null == this.f_inicio)  
        
        if (!(Hora.validarFormato(this.f_inicio.getText().trim()) && Hora.validarFormato(this.f_fin.getText().trim()))){
                 Notificacion notificacion = new Notificacion(this,true, "Ingrese el formato de hora valido, XX:XX");
                 notificacion.setVisible(true);
        }
            
        String carnet = f_carnet.getText().toString();
        if (!B_A_estudiante.validaCarnet(carnet)) {
                 Notificacion notificacion = new Notificacion(this,true,"Ingrese un carnet valido");
                 notificacion.setVisible(true);
        }
        
        if (!Hora.validarFormatoFecha(f_fecha.getText())) {
                Notificacion notificacion = new Notificacion(this,true,"Ingrese una fecha en el formato XX-XX-XXXX");
                notificacion.setVisible(true);
        } 
            
        if (null != B_A_estudiante.consultarEstudiante(carnet)){
                existe = true; 
        } else {
                 Notificacion notificacion = new Notificacion(this,true, "Ese estudiante no existe");
                 notificacion.setVisible(true);
        }
        
        if ((0 != this.f_inicio.getText().length()) && (0 != this.f_fin.getText().length())){
            inicioH = new Hora(this.f_inicio.getText().trim());
            finH = new Hora(this.f_fin.getText().trim());
            resultado = Hora.diferencia(inicioH, finH);
            if (!Hora.esMayor(inicioH, finH)){
               cumple = cumple & false;
               Notificacion notificacion = new Notificacion(this,true,"La hora de fin no debe ser menor que la hora de inicio");
               notificacion.setVisible(true);            
            } else {
                cumple = existe;
            }
        }
        
        if (cumple) {
        //Se registran las horas en la base de datos
             B_A_horas labor = new B_A_horas((this.f_carnet.getText()), finH, inicioH, this.f_fecha.getText(), this.f_obs.getText() ,resultado.toDouble());
             Boolean exito = labor.registrarLabor();
             Notificacion notificacion = new Notificacion(this,true,"Se inserto correctamente la información");
             notificacion.setVisible(true);
             Window ventana = new Window();
             ventana.setVisible(true);
             this.setVisible(false);
        } else  {
             Notificacion notificacion = new Notificacion(this,true,"Llene todos los campos e intente de nuevo");
             notificacion.setVisible(true);
        }
        
    }//GEN-LAST:event_agregarActionPerformed

    //accion del boton regresar
    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
      Window ventana = new Window();
      ventana.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
          if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
          }
        }
      } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Agregar_horas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Agregar_horas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Agregar_horas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Agregar_horas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          new Agregar_horas().setVisible(true);
        }
      });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carnet;
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel Obs;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField f_carnet;
    private javax.swing.JTextField f_fecha;
    private javax.swing.JTextField f_fin;
    private javax.swing.JTextField f_inicio;
    private javax.swing.JTextField f_obs;
    private javax.swing.JLabel fin;
    private javax.swing.JLabel fin1;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
