/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Graphic;

/**
 * Jform que permite consultal el total de horas
 * @author johndelgado
 */
public class Consulta_total extends javax.swing.JFrame {
  private Integer carnet;
  private B_A_estudiante estudiante;

  //constructor de la clase
  public Consulta_total(B_A_estudiante estudiante) {
    this.estudiante = estudiante;
    initComponents();
  }

  //getters & setters
  public B_A_estudiante getEstudiante() {
    return estudiante;
  }

  public void setEstudiante(B_A_estudiante estudiante) {
    this.estudiante = estudiante;
  }

  public Integer getCarnet() {
    return carnet;
  }

  public void setCarnet(Integer carnet) {
    this.carnet = carnet;
  }

  //constructor de la clase
  public Consulta_total() {
    initComponents();
  }

  //constructor de la clase
  public Consulta_total(Integer carnet_entrada) {
    carnet = carnet_entrada;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

      jButton1 = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      s_carnet = new javax.swing.JLabel();
      s_carnet1 = new javax.swing.JLabel();
      s_carnet2 = new javax.swing.JLabel();
      s_carnet3 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jButton1.setText("Regresar");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      });

      jLabel1.setText("Consultar el total de horas de un estudiante");

      jLabel2.setText("Carnet");

      jLabel3.setText("Nombres");

      jLabel4.setText("Apellidos");

      jLabel5.setText("Cantidad acumulada");

      s_carnet.setText(this.getEstudiante().getNombre().toString());

      s_carnet1.setText(String.valueOf(this.getEstudiante().getCarnet()));

      s_carnet2.setText(this.getEstudiante().getApellido());

      s_carnet3.setText(B_A_horas.consultarTotalHoras((this.getEstudiante().getCarnet())));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
              .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                    .addComponent(s_carnet3)
                    .addGap(79, 79, 79))
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel2)
                      .addComponent(jLabel4)
                      .addComponent(jLabel3))
                    .addGap(54, 54, 54)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(s_carnet)
                      .addComponent(s_carnet2)
                      .addComponent(s_carnet1))
                    .addGap(0, 0, Short.MAX_VALUE))))
              .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jLabel1)))
                  .addContainerGap())
                  );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(s_carnet1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(s_carnet))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(s_carnet2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(s_carnet3))
            .addGap(75, 75, 75)
            .addComponent(jButton1)
            .addContainerGap())
            );

      pack();
    }// </editor-fold>//GEN-END:initComponents

  //boton regresar
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Window ventana = new Window();
    ventana.setVisible(true);            
    this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Consulta_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Consulta_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Consulta_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Consulta_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>        
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {    
        new Consulta_total().setVisible(true);
      }

    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel s_carnet;
  private javax.swing.JLabel s_carnet1;
  private javax.swing.JLabel s_carnet2;
  private javax.swing.JLabel s_carnet3;
  // End of variables declaration//GEN-END:variables
}
