/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Graphic;

/**
 *
 * @author johndelgado
 */
public class Consulta_datos extends javax.swing.JFrame {
  private Integer carnet;
  private B_A_estudiante estudiante;

  //getters & setters
  public B_A_estudiante getEstudiante() {
    return estudiante;
  }

  public void setEstudiante(B_A_estudiante estudiante) {
    this.estudiante = estudiante;
  }

  public Integer getCarnet() {
    return carnet;
  }

  public void setCarnet(Integer carnet) {
    this.carnet = carnet;
  }
  /**
   * Creates new form Consulta_total
   * @param carnet
   */
  public Consulta_datos() {
    initComponents();
  }

  //constructor de la clase
  public Consulta_datos(Integer carnet_entrada) {
    carnet = carnet_entrada;
    initComponents();
  }

  //constructor de la clase
  public Consulta_datos(B_A_estudiante estudiante) {
    this.estudiante = estudiante;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

      jButton1 = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      s_nombre = new javax.swing.JLabel();
      s_carnet = new javax.swing.JLabel();
      s_apellido = new javax.swing.JLabel();
      s_direccion = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      s_telefono = new javax.swing.JLabel();
      s_estado = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jButton1.setText("Regresar");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      });

      jLabel1.setText("Consultar los datos de un estudiante");

      jLabel2.setText("Carnet");

      jLabel3.setText("Nombres");

      jLabel4.setText("Apellidos");

      s_nombre.setText(this.getEstudiante().getNombre().toString());

      s_carnet.setText(this.getEstudiante().getCarnet().toString());

      s_apellido.setText(this.getEstudiante().getApellido());

      s_direccion.setText(this.getEstudiante().getDireccion().toString());

      jLabel6.setText("Dirección");

      jLabel7.setText("Teléfono");

      jLabel8.setText("Estado");

      s_telefono.setText(this.getEstudiante().getCelular().toString());

      s_estado.setText(this.getEstudiante().getEstado().toString());

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel2)
                      .addComponent(jLabel4)
                      .addComponent(jLabel3)
                      .addComponent(jLabel6)
                      .addComponent(jLabel7)
                      .addComponent(jLabel8))
                    .addGap(54, 54, 54)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(s_nombre)
                      .addComponent(s_apellido)
                      .addComponent(s_carnet)
                      .addComponent(s_direccion)
                      .addComponent(s_estado)
                      .addComponent(s_telefono)))
                  .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)))
                    .addGap(0, 186, Short.MAX_VALUE)))
                    .addContainerGap())
                    );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(s_carnet))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(s_nombre))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(s_apellido))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel6)
              .addComponent(s_direccion))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel7)
              .addComponent(s_telefono))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(s_estado))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
            .addComponent(jButton1)
            .addContainerGap())
            );

      pack();
    }// </editor-fold>//GEN-END:initComponents

  //boton regresar
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Window ventana = new Window();
    ventana.setVisible(true);            
    this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Consulta_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Consulta_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Consulta_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Consulta_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>        
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {    
        new Consulta_datos().setVisible(true);
      }

    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel s_apellido;
  private javax.swing.JLabel s_carnet;
  private javax.swing.JLabel s_direccion;
  private javax.swing.JLabel s_estado;
  private javax.swing.JLabel s_nombre;
  private javax.swing.JLabel s_telefono;
  // End of variables declaration//GEN-END:variables
}
