/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Graphic;

/**
 *
 * @author johndelgado
 */
public class Modificar_estudiante extends javax.swing.JFrame {
    private Integer carnet;
    private B_A_estudiante estudiante;

    public B_A_estudiante getEstudiante() {
        return estudiante;
    }

    public Modificar_estudiante(B_A_estudiante estudiante) {
        this.estudiante = estudiante;
        initComponents();

    }

    public void setEstudiante(B_A_estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public Integer getCarnet() {
        return carnet;
    }

    public void setCarnet(Integer carnet) {
        this.carnet = carnet;
    }
    /**
     * Creates new form Consulta_total
     * @param carnet
     */
    public Modificar_estudiante() {
        initComponents();
    }
    
    public Modificar_estudiante(Integer carnet_entrada) {
        carnet = carnet_entrada;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s_carnet1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        s_direccion = new javax.swing.JTextField();
        s_nombre = new javax.swing.JTextField();
        s_apellido = new javax.swing.JTextField();
        s_estado = new javax.swing.JTextField();
        s_telefono = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        s_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cambiar los datos de un estudiante");

        jLabel2.setText("Carnet");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        s_carnet1.setText(this.getEstudiante().getCarnet().toString());

        jLabel6.setText("Dirección");

        jLabel7.setText("Teléfono");

        jLabel8.setText("Estado");

        s_direccion.setText(this.getEstudiante().getDireccion());

        s_nombre.setColumns(20);
        s_nombre.setText(this.getEstudiante().getNombre());
        s_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_nombreActionPerformed(evt);
            }
        });

        s_apellido.setText(this.getEstudiante().getApellido());

        s_estado.setText(this.getEstudiante().getEstado());

        s_telefono.setText(this.getEstudiante().getCelular());
        s_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_telefonoActionPerformed(evt);
            }
        });

        jButton2.setText("Cambiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("ACTIVO/INACTIVO");

        jLabel10.setText("Correo");

        s_email.setText(this.getEstudiante().getEmail());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(s_nombre)
                                    .addComponent(s_carnet1)
                                    .addComponent(s_apellido)
                                    .addComponent(s_direccion)
                                    .addComponent(s_telefono)
                                    .addComponent(s_estado)
                                    .addComponent(s_email)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s_carnet1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(s_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(s_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(s_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(s_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(s_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(s_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Window ventana = new Window();
        ventana.setVisible(true);            
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_telefonoActionPerformed

    private void s_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_nombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Boolean cumple = false;
        Boolean salida = false;
        
        while(!cumple){ 
          estudiante.setApellido(this.s_apellido.getText());
          estudiante.setNombre(this.s_nombre.getText());
          estudiante.setDireccion(this.s_direccion.getText());
          estudiante.setEstado(this.s_estado.getText());
          estudiante.setCelular(this.s_telefono.getText());
          estudiante.setEmail(this.s_email.getText());
        
          if (estudiante.getNombre().isEmpty()){
             Notificacion notificacion = new Notificacion(this,true, "Ingrese el nombre del estudiante");
             notificacion.setVisible(true);
          }
          
          if (estudiante.getApellido().isEmpty()){
             Notificacion notificacion = new Notificacion(this,true, "Ingrese el apellido de estudiante");
             notificacion.setVisible(true);
          }
          
          if (estudiante.getDireccion().isEmpty()){
             Notificacion notificacion = new Notificacion(this,true, "Ingrese una direccion del estudiante");
             notificacion.setVisible(true);
          }
          
          if (estudiante.getEmail().isEmpty()){
             Notificacion notificacion = new Notificacion(this,true, "Ingrese una direccion de correo electronico del estudiante");
             notificacion.setVisible(true);
          }
          
          if (estudiante.getEstado().isEmpty()){
             Notificacion notificacion = new Notificacion(this,true, "Ingrese el estado actual del estudiante en el sistema beta");
             notificacion.setVisible(true);
          }
          
          if (estudiante.getEstado().equalsIgnoreCase("ACTIVO")){
              estudiante.setEstado("ACTIVO");
          } else {
              if (estudiante.getEstado().equalsIgnoreCase("INACTIVO")){
                  estudiante.setEstado("INACTIVO");
              } else { 
                     Notificacion notificacion = new Notificacion(this,true, "Limitese a los estados ACTIVO/INACTIVO");
                     notificacion.setVisible(true);
              }
          }
          
          if (estudiante.getCelular().isEmpty()){
             Notificacion notificacion = new Notificacion(this,true, "Ingrese el numero de celular asociado al estudiante");
             notificacion.setVisible(true);
          } else {
            
            salida = true;
          }
          
          if (salida) {
        estudiante.modificarEstudiante();
                Notificacion notificacion = new Notificacion(this,true, "Se logró modificar al estudiante");
                notificacion.setVisible(true);
                break;

           } else {
                Notificacion notificacion = new Notificacion(this,true, "Intentelo nuevamente");
                notificacion.setVisible(true);
           }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {    
                new Modificar_estudiante().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField s_apellido;
    private javax.swing.JLabel s_carnet1;
    private javax.swing.JTextField s_direccion;
    private javax.swing.JTextField s_email;
    private javax.swing.JTextField s_estado;
    private javax.swing.JTextField s_nombre;
    private javax.swing.JTextField s_telefono;
    // End of variables declaration//GEN-END:variables
}
